# 参考资料
# https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
# https://vercel.com/guides/how-to-alias-a-preview-deployment-using-the-cli

name: 基于vercel命令的部署
env:
  vercel-token: ${{ secrets.vercel_token }}
  # 从教程内得知 环境变量名称必须大写
  VERCEL_ORG_ID: ${{ secrets.vercel_orgId }}
  VERCEL_PROJECT_ID: ${{ secrets.vercel_projectId }}

on:
  push:
    branches:
      - dev

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: 开启 corepack
        run: corepack enable && corepack install

      - name: 检查pnpm版本
        run: pnpm -v

      - name: 安装整个项目的依赖
        run: pnpm i

      - name: 用npm安装vercel cli工具
        run: npm i -g vercel@latest

      - name: 检查vercel cli版本
        run: vc -v

      - name: 连接现有的项目
        # 本地window使用
        # run: vc link --yes --cwd=./packages/monorepo-3 --project=vercel-monorepo-test-1-zn20
        run: vc link --yes --cwd=./packages/monorepo-3 --project=vercel-monorepo-test-1-zn20 -t ${{ secrets.vercel_token }}

      - name: vercel打包monorepo-3
        run: vc build --yes --prod --cwd=./packages/monorepo-3 -A ./vercel.null.json -t ${{ secrets.vercel_token }}
        # build命令仍然需要用token来运行。
        # run: vc build --yes --prod --cwd=./packages/monorepo-3 -A ./vercel.null.json

      - name: turbo并发运行打包命令
        run: pnpm run on-github-action-flow

      - name: 部署到vercel内
        run: |
          url="$(vc deploy --yes --prebuilt --prod --cwd=./packages/monorepo-3 -t ${{ secrets.vercel_token }})"
          vc alias -t ${{ secrets.vercel_token }} set "$url" monorepo-3.ruancat6312.top
